title:        Adopta Agency
url:          http://adopta.agency
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 25
paginate_path: "/blog/page:num"

production_url : http://adopta.agency

BASE_PATH : http://adopta.agency

categories_path : /categories.html
tags_path : /tags.html

# ---------
# Showcase
# ---------

showcase_show: yes
showcase_nav: no
showcase_title: Projects
showcase_description: This is a showcase of projects currently being developed as part of the Adopta.Agency work. We are just getting started, so come back often, or even better--get involved!
showcase_footer: While each project uses the same blueprint, each one is potentially different in how they approach improving on the data. Each data steward involved with Adopta can take their projects in the direction that makes best sense to them, other team members, and consumers.

showcase:
  - title: US Federal Budget
    owner: Kin Lane
    description: This is a project to make the US federal budget more machine readable, in hopes of building more meaningful tools on top of it. You can already access the historical budget via spreadsheets, but this project is work to make sure everything is available as CSV, JSON, as well as an active API.
    image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-open-budget.png
    url: http://kinlane.github.io/us-federal-budget/
  - title: VA Data Portal
    owner: Kin Lane
    description: This project is looking to move forward the conversation around VA data, making it more accessible as CSV and JSON files, and deploying simple APIs when I have the time. The VA needs help to make sure all of its vital assetts are machine readable by default.
    image: http://federal-government.apievangelist.com/images/logos/va.png
    url: http://va-data.github.io/adopta-va-portal/
  - title: US Department of Education Ed-Tech Data
    owner: Audrey Watters
    description: This project is drawn from the datasets about education and technology that are made available via data.gov.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/US-DeptOfEducation-Seal.svg.png
    url: http://audreywatters.github.io/usedgov_edtech_data/
  - title: My Brother's Keeper
    owner: Audrey Watters
    description: This project makes the data associated with President Obama's My Brother's Keeper initiative available in an open and editable format. By using the "Adopta.Agency" framework - that is, adopting Department of Education datasets - the data that the department has called "statistical indicators" for young men of color will be cleaned up, standardized, and made machine- and human-readable.
    image: http://adopta.agency/images/my-brothers-keeper.jpg
    url: http://audreywatters.github.io/mybrotherskeeper/
  - title: ClinicalTrials.gov
    owner: Kin Lane
    description: This is an open data project to the Clinical Trials and Transformation Iniative (CTTI) Aggregate Analysis of ClincalTrials.gov (AACT) Database, and deliver a simple web API, making the information more acessible, and usable in a variety of platforms and implementations.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/blog/clinical-trials-gov.png
    url: http://adopta-agency.github.io/clinical-trials/
